#+STARTUP: showeverything

Working heavily with Visual Studio Code and RUST I found some limitations about this IDE. Or better about its integration with the rust lsp-mode.
So I switched back to my previous editor, added a couple of improvements, it is just amazing.

I'm pushing my ideal configuration so that in the future I don't loose it. Most of the things you find here are taken from the amazin:

https://github.com/rksm/emacs-rust-config

* .emacs.d config for Rust

This accompanies my [[https://robert.kra.hn/posts/2021-02-07_rust-with-emacs/]["Configuring Emacs for Rust development" blog post]].

 It uses rust-anlyzer via rustic, lsp-mode, and lsp-ui-mode and also makes use of company, flycheck, and yasnippet. Among those features you get are

- Navigating the source code (go to to implementation, list references of symbols, outline structure of a file)
- Code completion ("intellisense")
- Code snippets
- Highlighting errors and warnings inline
- Apply code fixes and refactorings
- Automatically import definitions if necessary (such as Traits)
- Code formatting with rustfmt
- Building & running other cargo commands

The actual configuration lives in [[./init.el][init.el]]. Feel free to copy and paste as you see fit.

To run emacs with just this config, clone this repo, then:

#+begin_src shell
emacs -q --load "/path/to/standalone.el"
#+end_src

** License

[[./LICENSE][MIT licensed]]
