#+STARTUP: showeverything

Working heavily with Visual Studio Code and RUST I found some limitations about this IDE. Or better about its integration with the rust lsp-mode.
So I switched back to my previous editor, added a couple of improvements, it is just amazing.

I would actually suggest you to just download init.el to your ~/.emacs.d folder.
the first time you start you could get some errors some packages must be installed. If I have time I will ensure this config works without any normal intervention.

I'm pushing my previous ideal configuration so that in the future I don't loose it. Most of the things you find here are taken from the amazing:

https://github.com/rksm/emacs-rust-config

I did some changes, put some config together in order to help me start faster on a new configuration.
In order to make it work  clone to a specific folder:
#+begin_src shell
git clone git@github.com:virgiliolino/my-emacs-for-rust.git ~/resources-emacs
#+end_src

then start with ~/resources-emacs/emacs.sh

Why I'm not just overwriting the original .emacs.d folder? Well I personally like to try it fast if everything works fine.

* .emacs.d config for Rust

This accompanies my [[https://robert.kra.hn/posts/2021-02-07_rust-with-emacs/]["Configuring Emacs for Rust development" blog post]].

 It uses rust-anlyzer via rustic, lsp-mode, and lsp-ui-mode and also makes use of company, flycheck, and yasnippet. Among those features you get are

- Navigating the source code (go to to implementation, list references of symbols, outline structure of a file)
- Code completion ("intellisense")
- Code snippets
- Highlighting errors and warnings inline
- Apply code fixes and refactorings
- Automatically import definitions if necessary (such as Traits)
- Code formatting with rustfmt
- Building & running other cargo commands

The actual configuration lives in [[./init.el][init.el]]. Feel free to copy and paste as you see fit.

#+begin_src shell
emacs -q --load "/resources-emacs/standalone.el"
#+end_src

** License

[[./LICENSE][MIT licensed]]
